[bot]
# Boolean to tell if the bot is under maintenance or not
maintenance = false
# Boolean to tell if the bot is under test mode
test_mode = false
# Prefix used to prefix the MQTT topics and the databases. It must be the same for all the services.
prefix = "crownicles"

[mqtt]
# The MQTT server host
host = "mqtt://127.0.0.1"

[database]
# The host (ip or DNS) of the database
host = "127.0.0.1"
# The port of the database
port = 3306
# The user of the database
user = "crownicles"
# The password of a database user.
password = "secret_password"
# The root password, used to create the databases. Use this only in development. In production, leave the field empty and create the databases manually
root_password = "super_secret_password"

[logs]
# The log level of the bot. It can be one of: "error", "warn", "info", "debug"
level = "debug"
# The log locations. It can be one of: "console", "file", "loki"
locations = ["console", "file"]

[logs.loki]
# The loki host
host = ""
# Username to connect to loki
username = ""
# Password to connect to loki
password = ""

[others]
# Web server port. The web server is used to serve different utilities endpoints (metrics, log level configuration, maintenance, etc.)
webserver_port = 10123