export abstract class BlockingConstants {
	static readonly REASONS = {
		ACCEPT_ITEM: "acceptItem",
		CHIEF_GUILD_LEAVE: "chiefGuildLeave",
		CHOOSE_DESTINATION: "chooseDestination",
		CLASS: "class",
		DRINK: "drink",
		FIGHT: "fight",
		GOBLET_CHOOSE: "gobletChoose",
		GUILD_ADD: "guildInvite",
		GUILD_CREATE: "guildCreate",
		GUILD_DESCRIPTION: "guildDescription",
		GUILD_ELDER: "guildElder",
		GUILD_ELDER_REMOVE: "guildElderRemove",
		GUILD_KICK: "guildKick",
		GUILD_LEAVE: "guildLeave",
		GUILD_SHOP: "guildShop",
		LOTTERY: "lottery",
		MERCHANT: "merchant",
		MISSION_SHOP: "missionShop",
		PET_FEED: "petFeed",
		PET_FREE: "petFree",
		PET_SELL: "petSell",
		PET_SELL_CONFIRM: "petSellConfirm",
		PET_TRADE: "petTrade",
		REPORT: "report",
		SELL: "sell",
		SELL_CONFIRM: "sellConfirm",
		SHOP: "shop",
		SWITCH: "switch",
		TEST: "test",
		UNLOCK: "unlock"
	};
}