[global]
# Prefix used to prefix the MQTT topics and the databases
prefix = "crownicles"

[restApi]
# Allow registering of new users
allowRegister = true
# Port to run the REST API on
port = 10500
# Beta authentication. If true, only keycloak users with the "beta" role can log in to the API
betaLogin = false

[restApi.discordSso]
# Discord SSO client ID
clientId = ""
# Discord SSO client secret
clientSecret = ""
# Discord SSO callback URL without the route (ex: http://localhost:10500)
# The callback URL must be the same as the one configured in the Discord developer portal with /discord/callback at the end in the developer portal
callbackUrl = ""

[webSocket]
# Port to run the WebSocket server on
port = 10501

[mqtt]
# MQTT host
host = "mqtt://127.0.0.1"

[keycloak]
# Keycloak realm
realm = "Crownicles"
# Keycloak URL
url = "http://127.0.0.1:8080"
# Keycloak client ID
clientId = "restWs"
# Keycloak client secret
clientSecret = ""

[logs]
# The log level of the bot. It can be one of: "error", "warn", "info", "debug"
level = "info"
# The log locations. It can be one of: "console", "file", "loki"
locations = ["console", "file"]

[logs.loki]
# The loki host
host = "http://127.0.0.1:3100"
# Username to connect to loki
username = ""
# Password to connect to loki
password = ""
